// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/phenpessoa/br"
)

type Cliente struct {
	ID       int64
	Cpf      br.CPF
	Nome     string
	Endereco string
	Email    string
}

type ClientesPet struct {
	ID        int64
	ClienteID int64
	Nome      string
	Raca      string
	Especie   string
}

type ClientesTelefone struct {
	ClienteID int64
	Telefone  string
}
